[package]
name = "koru-kafe"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.28.2", features = ["full"] }
hyper = { version = "0.14.26", features = ["http1", "http2", "server", "client", "runtime", "tcp", "stream"] }
fastwebsockets = { version = "0.4.2", features = ["upgrade"] }
mime_guess = "2.0.4"
bytes = "1.4.0"
directories = "5.0.1"
yaml-rust = "0.4.5"
serde = "1.0.163"
serde_derive = "1.0.163"
radix_trie = "0.2.1"
lazy_static = "1.4.0"
async-trait = "0.1.68"
tokio-rustls = "0.24.0"
rustls-pemfile = "1.0.2"
env_logger = "0.10.0"
log = "0.4.18"
httpdate = "1.0.2"

[dev-dependencies]
tokio-test = "0.4.2"
